### PR TITLE
Add partial Dutch translation

### PR DESCRIPTION
**Pull request by siebrand**

### CODE REVIEW

**Comment by siebrand** [comment]
I though I had push access to the repo, but apparently it's been removed again. Can you please re-add it, so that I can also push localisation updates from translatewiki.net? Thanks.

**Comment by siebrand** [comment]
@lbayle Please merge that, and also see the above comment.

**Comment by lbayle** [comment]
Hi Siebrand,
I'm sorry I was not clear in my mind on how to organize these access rights.
There is another github repository where I'd prefer you to do the commits:

https://github.com/mantisbt-plugins/codev

on that one, I'm quite sure that you have access rights: I added them 2
weeks ago, if mantis team did not remove them, it should be ok !

thank you for the contribution !

Louis

Louis BAYLE
Tel: +33 (0)4.42.604.734
lbayle.work@gmail.com

On Fri, Feb 19, 2016 at 2:55 PM, Siebrand Mazeland <notifications@github.com

**Comment by siebrand** [comment]
Check. I'm updating the repo location.

**Pull request merged**
